add amount to object returned by endpoint
hypesystem/maerkelex-payment pull request #77
Opened 2024-07-09 11:56 UTC by Rad1calp

adds a field to the object that is returned by /admin/orders that contains the total amount of orders.
Another step towards the pagination of /admin.
Little unsure if it should query twice(current implementation) or slice a full query, to fit limit and offset.

2024-08-29 13:09 UTC, Rad1calp commented on purchases/index.js
> +        db.query(`SELECT * FROM purchase ORDER BY started_at DESC`, (error, result) => {
still unsure of this query twice implementation. Just doesn't look nice with nested all most identical db lookups

2024-08-30 07:28 UTC, hypesystem requested changes
Revert this commit, and instead look into SQL COUNT-expressions, c.f. e.g. https://stackoverflow.com/a/28916930/1080564

2024-08-30 07:28 UTC, hypesystem commented on purchases/index.js
> +        })
This is a terribly slow approach. You end up getting all the orders, serializing them and sending them to the server application, which then deserializes them, counts them, and responds with a number.

When possible always push the work to the database. Revert this commit, and instead look into SQL COUNT-expressions, c.f. e.g. https://stackoverflow.com/a/28916930/1080564

2024-08-30 07:28 UTC, hypesystem commented on purchases/index.js
> +        if(limitedError) {
Don't rename `error` - it is convention to use that name for every error, and it is okay to overload the name in later calls.

Same for the result honestly. `limitedResult` means very little to me. If you want a different name, it should denote the purpose. The first query is for results, the second is for a count of results. Use that in the naming.

2024-08-30 12:27 UTC, merged